update function to be able to source the config files after running the function

diff --git a/bin/editrc b/bin/editrc
--- a/bin/editrc
+++ b/bin/editrc
@@ -66,7 +66,7 @@ if [ "$#" -eq 0 ]; then
   # Run the usage function
   usage
 
-  exit 1
+  return 1
 
 fi
 
@@ -95,18 +95,24 @@ if [ -n "$1" ]; then
     # Show the usage information
     usage
 
-    exit 1
+    return 1
     ;;
   esac
 
   # Reload the source after updating the config files
-  # 'urc' is an alias to source the Terminal to ~/.zshrc
-  urc
 
-  # Then exit successfully
-  exit 0
+  if ! source ~/.zshrc; then
+    echo >&2 -e "${RED}[ERROR]${NS}: Error updating the shell with the changes: [EXIT: $?]\n"
+    echo >&2 -e "Try manually updating the config with '${ITALIC}urc${NS}' ${BOLD}OR${NS} '${ITALIC}. ~/.zshrc${NS}'"
+    return 1
+  else
+    echo -e "${GREEN}SUCCESSFULLY UPDATED CONFIG${NS}"
 
-# Otherwise, just default to editing the $configrc rc file
+    # Then exit successfully
+    return 0
+  fi
+
+# Otherwise, throw an error and print the usage information
 else
 
   # Open the $configrc file in nano
@@ -114,6 +120,6 @@ else
 
   usage
 
-  exit 1
+  return 1
 
 fi
